[package]
name = "zkwasm-rlp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
num-bigint = "0.4.3"
rlp = { version = "0.5.2"}
wasm-bindgen = "0.2.83"
